# Generated by Django 3.0.4 on 2020-08-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='', max_length=9),
        ),
    ]
