# Generated by Django 3.0.4 on 2020-08-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechLab', '0002_paciente_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='', max_length=9, primary_key=True, serialize=False),
        ),
    ]
