# Generated by Django 3.0.4 on 2020-08-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechLab', '0003_auto_20200813_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='', max_length=9, unique=True),
        ),
    ]
