# Generated by Django 3.0.4 on 2020-08-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechLab', '0005_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hora',
            field=models.TimeField(),
        ),
    ]
