# Generated by Django 3.0.4 on 2020-08-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechLab', '0007_auto_20200814_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='hora',
            field=models.CharField(max_length=100),
        ),
    ]
