# Generated by Django 2.1.7 on 2019-06-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0003_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
