# Generated by Django 2.1.7 on 2019-06-24 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0005_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='horario_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_asig', to='Horarios.Horario'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dias_disp',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
    ]
