# Generated by Django 2.1.7 on 2019-06-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0006_auto_20190624_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dias_disp',
            field=models.CharField(default='', max_length=500),
        ),
    ]
