# Generated by Django 2.1.7 on 2019-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0007_auto_20190624_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='dias_disp',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
