# Generated by Django 2.1.7 on 2019-07-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horarios', '0008_auto_20190625_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='comentarios',
            field=models.CharField(default='Sin comentarios', max_length=1000),
        ),
    ]
